# Site settings
title:       Nathan Sweet's Blog
email:       nathanjsweet@gmail.com
author:      Nathan Sweet
description: "Nathan Sweet's thoughts on computer programming, protips, and, hopefully, not too many rants..."
baseurl:     ""
url:         "http://nathansweet.me"
date_format: "%b %-d, %Y"

# Google services
google_analytics:	UA-19117226-1
google_verification:

# Optional features
animated:             false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Social icons
github_username: nathanjsweet

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:year/:month/:day/:title
paginate:     10
sass:
  compressed: true
